removed_sources:
  HTML_QuickForm_Renderer_Tableless-0.5.3.tgz: b6b2eb1b91d331c7df0c095cfd347da6fc0c75f8
sources:
  HTML_QuickForm_Renderer_Tableless-0.6.2.tgz: 5ffac385b661a4acbbaeb75f26eec7200e7d6d41
